# Generated by Django 5.2.16 on 2026-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_actif',
            field=models.BooleanField(default=False),
        ),
    ]
