# Generated by Django 5.2.16 on 2026-08-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0002_produit_is_actif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
