# Generated by Django 5.2.16 on 2026-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=1, max_digits=10)),
                ('quantite', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('le_produit_est_actif', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Medicament',
                'verbose_name_plural': 'Medicaments',
            },
        ),
    ]
