# Generated by Django 5.2.16 on 2026-08-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'verbose_name': 'Medicament'},
        ),
    ]
