# Generated by Django 5.2.16 on 2026-08-25 11:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, help_text='Allergies, traitements en cours...')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'entreprise")),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Prix de vente (€)')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(0)], verbose_name="Prix d'achat en (€)")),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantinte en stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, verbose_name='Seuil alerte')),
                ('lot', models.CharField(blank=True, max_length=50, verbose_name='Numerro de lot')),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('description', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.categorie')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.fournisseur')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile money')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('payee', 'Payee'), ('en_entente', 'En antente'), ('impayee', 'Impayee'), ('annulee', 'Annulee')], default='impayee', max_length=20)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise en (€)')),
                ('client', models.ForeignKey(blank=True, help_text='vide = client de passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='produits.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de la vente en (£)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Lignes_vente', to='produits.produit')),
                ('Vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.vente')),
            ],
        ),
    ]
